name: Publish Yarn libs
description: Publish project artifacts using Yarn.

inputs:
  project-type:
    required: false
    default: singlerepo
    description: Is `monorepo` or `singlerepo` project.
runs:
  using: composite
  steps:
    - run: yarn workspaces foreach --topological-dev --no-private --since='HEAD~1' npm publish --tolerate-republish
      shell: bash
      if: inputs.project-type == 'monorepo'
    - run: |
        if [ -f "./dist/package.json" ]; then
          touch ./dist/yarn.lock
          cd ./dist
          yarn install
        fi
        yarn npm publish --tolerate-republish
      shell: bash
      if: inputs.project-type == 'singlerepo'
